"""add website content gallery and press tables

Revision ID: 0ab3801697ae
Revises: 9e6c25838d3b
Create Date: 2026-10-09 17:28:47.533339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab3801697ae'
down_revision: Union[str, Sequence[str], None] = '9e6c25838d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_section_headers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('badge', sa.String(length=255), nullable=True),
    sa.Column('heading1', sa.String(length=255), nullable=True),
    sa.Column('heading2', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=150), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_photos',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_photos_category'), 'gallery_photos', ['category'], unique=False)
    op.create_index(op.f('ix_gallery_photos_created_by_admin_id'), 'gallery_photos', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_gallery_photos_display_order'), 'gallery_photos', ['display_order'], unique=False)
    op.create_index(op.f('ix_gallery_photos_id'), 'gallery_photos', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_photos_is_published'), 'gallery_photos', ['is_published'], unique=False)
    op.create_index(op.f('ix_gallery_photos_title'), 'gallery_photos', ['title'], unique=False)
    op.create_table('gallery_videos',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('youtube_url', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_videos_category'), 'gallery_videos', ['category'], unique=False)
    op.create_index(op.f('ix_gallery_videos_created_by_admin_id'), 'gallery_videos', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_gallery_videos_display_order'), 'gallery_videos', ['display_order'], unique=False)
    op.create_index(op.f('ix_gallery_videos_id'), 'gallery_videos', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_videos_is_published'), 'gallery_videos', ['is_published'], unique=False)
    op.create_index(op.f('ix_gallery_videos_title'), 'gallery_videos', ['title'], unique=False)
    op.create_table('press_articles',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('newspaper', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('edition', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_press_articles_category'), 'press_articles', ['category'], unique=False)
    op.create_index(op.f('ix_press_articles_created_by_admin_id'), 'press_articles', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_press_articles_display_order'), 'press_articles', ['display_order'], unique=False)
    op.create_index(op.f('ix_press_articles_id'), 'press_articles', ['id'], unique=False)
    op.create_index(op.f('ix_press_articles_is_published'), 'press_articles', ['is_published'], unique=False)
    op.create_index(op.f('ix_press_articles_newspaper'), 'press_articles', ['newspaper'], unique=False)
    op.create_index(op.f('ix_press_articles_title'), 'press_articles', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_press_articles_title'), table_name='press_articles')
    op.drop_index(op.f('ix_press_articles_newspaper'), table_name='press_articles')
    op.drop_index(op.f('ix_press_articles_is_published'), table_name='press_articles')
    op.drop_index(op.f('ix_press_articles_id'), table_name='press_articles')
    op.drop_index(op.f('ix_press_articles_display_order'), table_name='press_articles')
    op.drop_index(op.f('ix_press_articles_created_by_admin_id'), table_name='press_articles')
    op.drop_index(op.f('ix_press_articles_category'), table_name='press_articles')
    op.drop_table('press_articles')
    op.drop_index(op.f('ix_gallery_videos_title'), table_name='gallery_videos')
    op.drop_index(op.f('ix_gallery_videos_is_published'), table_name='gallery_videos')
    op.drop_index(op.f('ix_gallery_videos_id'), table_name='gallery_videos')
    op.drop_index(op.f('ix_gallery_videos_display_order'), table_name='gallery_videos')
    op.drop_index(op.f('ix_gallery_videos_created_by_admin_id'), table_name='gallery_videos')
    op.drop_index(op.f('ix_gallery_videos_category'), table_name='gallery_videos')
    op.drop_table('gallery_videos')
    op.drop_index(op.f('ix_gallery_photos_title'), table_name='gallery_photos')
    op.drop_index(op.f('ix_gallery_photos_is_published'), table_name='gallery_photos')
    op.drop_index(op.f('ix_gallery_photos_id'), table_name='gallery_photos')
    op.drop_index(op.f('ix_gallery_photos_display_order'), table_name='gallery_photos')
    op.drop_index(op.f('ix_gallery_photos_created_by_admin_id'), table_name='gallery_photos')
    op.drop_index(op.f('ix_gallery_photos_category'), table_name='gallery_photos')
    op.drop_table('gallery_photos')
    op.drop_table('website_section_headers')
    # ### end Alembic commands ###
