"""add recruiter jobs and interviews tables

Revision ID: 67155c451a18
Revises: bbff8f3f20d8
Create Date: 2026-10-05 18:41:31.177356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67155c451a18'
down_revision: Union[str, Sequence[str], None] = 'bbff8f3f20d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('recruiter_id', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('work_mode', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('experience', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.Column('openings', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('deadline', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiter_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_company_name'), 'jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_jobs_recruiter_id'), 'jobs', ['recruiter_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('interviews',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('interview_number', sa.String(length=50), nullable=True),
    sa.Column('recruiter_id', sa.String(length=50), nullable=False),
    sa.Column('candidate_profile_id', sa.String(length=50), nullable=True),
    sa.Column('application_id', sa.String(length=50), nullable=True),
    sa.Column('job_id', sa.String(length=50), nullable=True),
    sa.Column('candidate_name', sa.String(length=150), nullable=False),
    sa.Column('candidate_email', sa.String(length=150), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('round_name', sa.String(length=100), nullable=False),
    sa.Column('interview_type', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=100), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('meeting_platform', sa.String(length=100), nullable=False),
    sa.Column('meeting_link', sa.String(length=255), nullable=True),
    sa.Column('interviewer', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['candidate_applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiter_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_application_id'), 'interviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_interviews_candidate_profile_id'), 'interviews', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.create_index(op.f('ix_interviews_interview_number'), 'interviews', ['interview_number'], unique=False)
    op.create_index(op.f('ix_interviews_job_id'), 'interviews', ['job_id'], unique=False)
    op.create_index(op.f('ix_interviews_recruiter_id'), 'interviews', ['recruiter_id'], unique=False)
    op.create_index(op.f('ix_interviews_scheduled_at'), 'interviews', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.add_column('candidate_applications', sa.Column('recruiter_id', sa.String(length=50), nullable=True))
    op.add_column('candidate_applications', sa.Column('match_percentage', sa.Integer(), nullable=True))
    op.add_column('candidate_applications', sa.Column('experience', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_candidate_applications_recruiter_id'), 'candidate_applications', ['recruiter_id'], unique=False)
    op.create_foreign_key('fk_candidate_applications_recruiter_id', 'candidate_applications', 'recruiter_profiles', ['recruiter_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_candidate_applications_recruiter_id', 'candidate_applications', type_='foreignkey')
    op.drop_index(op.f('ix_candidate_applications_recruiter_id'), table_name='candidate_applications')
    op.drop_column('candidate_applications', 'experience')
    op.drop_column('candidate_applications', 'match_percentage')
    op.drop_column('candidate_applications', 'recruiter_id')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_scheduled_at'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_recruiter_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_job_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_interview_number'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_candidate_profile_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_application_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_recruiter_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_name'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
