"""add company team members invitations and notification preferences

Revision ID: 7c705b6a9362
Revises: e5504d90bca0
Create Date: 2026-10-06 14:45:41.170301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c705b6a9362'
down_revision: Union[str, Sequence[str], None] = 'e5504d90bca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiter_notification_preferences',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('instant_new_applicant_alerts', sa.Boolean(), nullable=False),
    sa.Column('interview_confirmation_reminders', sa.Boolean(), nullable=False),
    sa.Column('weekly_hiring_digest', sa.Boolean(), nullable=False),
    sa.Column('job_mela_alerts', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_notification_preferences_id'), 'recruiter_notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_recruiter_notification_preferences_user_id'), 'recruiter_notification_preferences', ['user_id'], unique=True)
    op.create_table('company_invitations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('invited_by', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['recruiter_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_invitations_company_id'), 'company_invitations', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_invitations_email'), 'company_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_company_invitations_id'), 'company_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_company_invitations_token_hash'), 'company_invitations', ['token_hash'], unique=False)
    op.create_table('company_members',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('invited_by', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['recruiter_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_company_user')
    )
    op.create_index(op.f('ix_company_members_company_id'), 'company_members', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_members_id'), 'company_members', ['id'], unique=False)
    op.create_index(op.f('ix_company_members_status'), 'company_members', ['status'], unique=False)
    op.create_index(op.f('ix_company_members_user_id'), 'company_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_members_user_id'), table_name='company_members')
    op.drop_index(op.f('ix_company_members_status'), table_name='company_members')
    op.drop_index(op.f('ix_company_members_id'), table_name='company_members')
    op.drop_index(op.f('ix_company_members_company_id'), table_name='company_members')
    op.drop_table('company_members')
    op.drop_index(op.f('ix_company_invitations_token_hash'), table_name='company_invitations')
    op.drop_index(op.f('ix_company_invitations_id'), table_name='company_invitations')
    op.drop_index(op.f('ix_company_invitations_email'), table_name='company_invitations')
    op.drop_index(op.f('ix_company_invitations_company_id'), table_name='company_invitations')
    op.drop_table('company_invitations')
    op.drop_index(op.f('ix_recruiter_notification_preferences_user_id'), table_name='recruiter_notification_preferences')
    op.drop_index(op.f('ix_recruiter_notification_preferences_id'), table_name='recruiter_notification_preferences')
    op.drop_table('recruiter_notification_preferences')
    # ### end Alembic commands ###
