"""add reports table

Revision ID: 861fb3227351
Revises: 51db14676fd4
Create Date: 2026-10-08 15:32:57.003434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861fb3227351'
down_revision: Union[str, Sequence[str], None] = '51db14676fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('reported_user_type', sa.String(length=50), nullable=False),
    sa.Column('reported_user_id', sa.String(length=50), nullable=True),
    sa.Column('reported_entity_type', sa.String(length=50), nullable=False),
    sa.Column('reported_entity_id', sa.String(length=100), nullable=True),
    sa.Column('reported_entity_name', sa.String(length=255), nullable=True),
    sa.Column('reporter_user_id', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('resolution_reason', sa.String(length=255), nullable=True),
    sa.Column('resolved_by_admin_id', sa.String(length=50), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_by_admin_id', sa.String(length=50), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dismissed_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_dismissed_by_admin_id'), 'reports', ['dismissed_by_admin_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_number'), 'reports', ['report_number'], unique=True)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_reported_entity_id'), 'reports', ['reported_entity_id'], unique=False)
    op.create_index(op.f('ix_reports_reported_entity_name'), 'reports', ['reported_entity_name'], unique=False)
    op.create_index(op.f('ix_reports_reported_entity_type'), 'reports', ['reported_entity_type'], unique=False)
    op.create_index(op.f('ix_reports_reported_user_id'), 'reports', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_reports_reported_user_type'), 'reports', ['reported_user_type'], unique=False)
    op.create_index(op.f('ix_reports_reporter_user_id'), 'reports', ['reporter_user_id'], unique=False)
    op.create_index(op.f('ix_reports_resolved_by_admin_id'), 'reports', ['resolved_by_admin_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_resolved_by_admin_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_user_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_entity_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_entity_name'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_entity_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_number'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_dismissed_by_admin_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
