"""add recruiter profiles table

Revision ID: a79f8a35f92b
Revises: 921a81d38c74
Create Date: 2026-10-05 15:59:34.480094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79f8a35f92b'
down_revision: Union[str, Sequence[str], None] = '921a81d38c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiter_profiles',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('recruiter_name', sa.String(length=150), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=False),
    sa.Column('work_email', sa.String(length=150), nullable=False),
    sa.Column('mobile_phone', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_website', sa.String(length=255), nullable=False),
    sa.Column('corporate_email', sa.String(length=150), nullable=True),
    sa.Column('company_phone', sa.String(length=20), nullable=True),
    sa.Column('primary_industry', sa.String(length=100), nullable=False),
    sa.Column('company_size', sa.String(length=100), nullable=False),
    sa.Column('headquarters_city_state', sa.String(length=150), nullable=False),
    sa.Column('registered_office_address', sa.Text(), nullable=False),
    sa.Column('company_description', sa.Text(), nullable=False),
    sa.Column('incorporation_document_path', sa.String(length=500), nullable=False),
    sa.Column('recruiter_authorization_document_path', sa.String(length=500), nullable=False),
    sa.Column('company_logo_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_profiles_company_name'), 'recruiter_profiles', ['company_name'], unique=False)
    op.create_index(op.f('ix_recruiter_profiles_id'), 'recruiter_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_recruiter_profiles_mobile_phone'), 'recruiter_profiles', ['mobile_phone'], unique=True)
    op.create_index(op.f('ix_recruiter_profiles_status'), 'recruiter_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_recruiter_profiles_user_id'), 'recruiter_profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_recruiter_profiles_work_email'), 'recruiter_profiles', ['work_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruiter_profiles_work_email'), table_name='recruiter_profiles')
    op.drop_index(op.f('ix_recruiter_profiles_user_id'), table_name='recruiter_profiles')
    op.drop_index(op.f('ix_recruiter_profiles_status'), table_name='recruiter_profiles')
    op.drop_index(op.f('ix_recruiter_profiles_mobile_phone'), table_name='recruiter_profiles')
    op.drop_index(op.f('ix_recruiter_profiles_id'), table_name='recruiter_profiles')
    op.drop_index(op.f('ix_recruiter_profiles_company_name'), table_name='recruiter_profiles')
    op.drop_table('recruiter_profiles')
    # ### end Alembic commands ###
