"""add candidate applications and timeline events

Revision ID: cf896d62ef10
Revises: 56e9ff416e51
Create Date: 2026-10-05 16:38:56.518158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf896d62ef10'
down_revision: Union[str, Sequence[str], None] = '56e9ff416e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_applications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False),
    sa.Column('candidate_profile_id', sa.String(length=50), nullable=False),
    sa.Column('job_id', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=False),
    sa.Column('work_mode', sa.String(length=50), nullable=False),
    sa.Column('application_type', sa.String(length=100), nullable=False),
    sa.Column('mela_id', sa.String(length=50), nullable=True),
    sa.Column('mela_title', sa.String(length=255), nullable=True),
    sa.Column('event_number', sa.String(length=50), nullable=True),
    sa.Column('company_sequence', sa.String(length=50), nullable=True),
    sa.Column('application_sequence', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_date', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('resume_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_applications_application_number'), 'candidate_applications', ['application_number'], unique=True)
    op.create_index(op.f('ix_candidate_applications_candidate_profile_id'), 'candidate_applications', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_candidate_applications_id'), 'candidate_applications', ['id'], unique=False)
    op.create_index(op.f('ix_candidate_applications_job_id'), 'candidate_applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_candidate_applications_status'), 'candidate_applications', ['status'], unique=False)
    op.create_table('application_timeline_events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['candidate_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_timeline_events_application_id'), 'application_timeline_events', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_timeline_events_id'), 'application_timeline_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_timeline_events_id'), table_name='application_timeline_events')
    op.drop_index(op.f('ix_application_timeline_events_application_id'), table_name='application_timeline_events')
    op.drop_table('application_timeline_events')
    op.drop_index(op.f('ix_candidate_applications_status'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_job_id'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_id'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_candidate_profile_id'), table_name='candidate_applications')
    op.drop_index(op.f('ix_candidate_applications_application_number'), table_name='candidate_applications')
    op.drop_table('candidate_applications')
    # ### end Alembic commands ###
