"""add tagline cin and gst to recruiter profiles

Revision ID: e5504d90bca0
Revises: 55809c7ebb0f
Create Date: 2026-10-06 14:16:28.900220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5504d90bca0'
down_revision: Union[str, Sequence[str], None] = '55809c7ebb0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiter_profiles', sa.Column('tagline', sa.String(length=300), nullable=True))
    op.add_column('recruiter_profiles', sa.Column('cin_number', sa.String(length=50), nullable=True))
    op.add_column('recruiter_profiles', sa.Column('gst_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiter_profiles', 'gst_number')
    op.drop_column('recruiter_profiles', 'cin_number')
    op.drop_column('recruiter_profiles', 'tagline')
    # ### end Alembic commands ###
