"""add candidate settings table

Revision ID: e8581e2bd86d
Revises: ed85dd0acfa8
Create Date: 2026-10-05 17:54:10.676934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8581e2bd86d'
down_revision: Union[str, Sequence[str], None] = 'ed85dd0acfa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_settings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('candidate_id', sa.String(length=50), nullable=False),
    sa.Column('email_job_application_alerts', sa.Boolean(), nullable=False),
    sa.Column('sms_whatsapp_notifications', sa.Boolean(), nullable=False),
    sa.Column('upcoming_interview_reminders', sa.Boolean(), nullable=False),
    sa.Column('weekly_job_recommendation_digest', sa.Boolean(), nullable=False),
    sa.Column('visible_in_recruiter_talent_search', sa.Boolean(), nullable=False),
    sa.Column('direct_recruiter_messages', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_settings_candidate_id'), 'candidate_settings', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_candidate_settings_id'), 'candidate_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_settings_id'), table_name='candidate_settings')
    op.drop_index(op.f('ix_candidate_settings_candidate_id'), table_name='candidate_settings')
    op.drop_table('candidate_settings')
    # ### end Alembic commands ###
