"""add candidate profile details, skills, experiences, educations, certifications, projects, resumes

Revision ID: ed85dd0acfa8
Revises: 7e7cadf39f99
Create Date: 2026-10-05 17:19:33.407071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed85dd0acfa8'
down_revision: Union[str, Sequence[str], None] = '7e7cadf39f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_certifications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('candidate_profile_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('year', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_certifications_candidate_profile_id'), 'candidate_certifications', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_candidate_certifications_id'), 'candidate_certifications', ['id'], unique=False)
    op.create_table('candidate_educations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('candidate_profile_id', sa.String(length=50), nullable=False),
    sa.Column('degree', sa.String(length=150), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('score', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_educations_candidate_profile_id'), 'candidate_educations', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_candidate_educations_id'), 'candidate_educations', ['id'], unique=False)
    op.create_table('candidate_experiences',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('candidate_profile_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_experiences_candidate_profile_id'), 'candidate_experiences', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_candidate_experiences_id'), 'candidate_experiences', ['id'], unique=False)
    op.create_table('candidate_projects',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('candidate_profile_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('tech', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_projects_candidate_profile_id'), 'candidate_projects', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_candidate_projects_id'), 'candidate_projects', ['id'], unique=False)
    op.create_table('candidate_resumes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('candidate_profile_id', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_resumes_candidate_profile_id'), 'candidate_resumes', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_candidate_resumes_id'), 'candidate_resumes', ['id'], unique=False)
    op.create_table('candidate_skills',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('candidate_profile_id', sa.String(length=50), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_profile_id', 'skill_name', name='uq_candidate_skill')
    )
    op.create_index(op.f('ix_candidate_skills_candidate_profile_id'), 'candidate_skills', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_candidate_skills_id'), 'candidate_skills', ['id'], unique=False)
    op.add_column('candidate_profiles', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('candidate_profiles', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('candidate_profiles', sa.Column('github_url', sa.String(length=255), nullable=True))
    op.add_column('candidate_profiles', sa.Column('portfolio_url', sa.String(length=255), nullable=True))
    op.add_column('candidate_profiles', sa.Column('avatar', sa.Text(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('total_experience', sa.String(length=100), nullable=True))
    op.add_column('candidate_profiles', sa.Column('current_salary', sa.String(length=100), nullable=True))
    op.add_column('candidate_profiles', sa.Column('expected_salary_min', sa.String(length=100), nullable=True))
    op.add_column('candidate_profiles', sa.Column('expected_salary_max', sa.String(length=100), nullable=True))
    op.add_column('candidate_profiles', sa.Column('expected_salary', sa.String(length=150), nullable=True))
    op.add_column('candidate_profiles', sa.Column('work_mode', sa.String(length=50), nullable=True))
    op.add_column('candidate_profiles', sa.Column('employment_type', sa.String(length=50), nullable=True))
    op.add_column('candidate_profiles', sa.Column('preferred_job_roles', sa.Text(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('preferred_locations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_profiles', 'preferred_locations')
    op.drop_column('candidate_profiles', 'preferred_job_roles')
    op.drop_column('candidate_profiles', 'employment_type')
    op.drop_column('candidate_profiles', 'work_mode')
    op.drop_column('candidate_profiles', 'expected_salary')
    op.drop_column('candidate_profiles', 'expected_salary_max')
    op.drop_column('candidate_profiles', 'expected_salary_min')
    op.drop_column('candidate_profiles', 'current_salary')
    op.drop_column('candidate_profiles', 'total_experience')
    op.drop_column('candidate_profiles', 'avatar')
    op.drop_column('candidate_profiles', 'portfolio_url')
    op.drop_column('candidate_profiles', 'github_url')
    op.drop_column('candidate_profiles', 'linkedin_url')
    op.drop_column('candidate_profiles', 'location')
    op.drop_index(op.f('ix_candidate_skills_id'), table_name='candidate_skills')
    op.drop_index(op.f('ix_candidate_skills_candidate_profile_id'), table_name='candidate_skills')
    op.drop_table('candidate_skills')
    op.drop_index(op.f('ix_candidate_resumes_id'), table_name='candidate_resumes')
    op.drop_index(op.f('ix_candidate_resumes_candidate_profile_id'), table_name='candidate_resumes')
    op.drop_table('candidate_resumes')
    op.drop_index(op.f('ix_candidate_projects_id'), table_name='candidate_projects')
    op.drop_index(op.f('ix_candidate_projects_candidate_profile_id'), table_name='candidate_projects')
    op.drop_table('candidate_projects')
    op.drop_index(op.f('ix_candidate_experiences_id'), table_name='candidate_experiences')
    op.drop_index(op.f('ix_candidate_experiences_candidate_profile_id'), table_name='candidate_experiences')
    op.drop_table('candidate_experiences')
    op.drop_index(op.f('ix_candidate_educations_id'), table_name='candidate_educations')
    op.drop_index(op.f('ix_candidate_educations_candidate_profile_id'), table_name='candidate_educations')
    op.drop_table('candidate_educations')
    op.drop_index(op.f('ix_candidate_certifications_id'), table_name='candidate_certifications')
    op.drop_index(op.f('ix_candidate_certifications_candidate_profile_id'), table_name='candidate_certifications')
    op.drop_table('candidate_certifications')
    # ### end Alembic commands ###
